apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: {{ CLIENT_NAMESPACE }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
  - host: {{ CLIENT_NAMESPACE }}.wp.framework.t4gc.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80

  tls:
  - hosts:
    - {{ CLIENT_NAMESPACE }}.wp.framework.t4gc.in
    secretName: {{ CLIENT_NAMESPACE }}.tls